swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /espacios_fisicos_mid/ActivarEspacioFisico/{id}:
    put:
      tags:
      - espacios_fisicos_mid
      description: Activar el espacio fisico
      operationId: GestionEspaciosFisicosController.PutActivarEspacioFisico
      parameters:
      - in: body
        name: body
        description: body Activar Espacio Fisico content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "400":
          description: the request contains incorrect syntax
  /espacios_fisicos_mid/BuscarEspacioFisico:
    post:
      tags:
      - espacios_fisicos_mid
      description: Buscar Espacio Fisico
      operationId: GestionEspaciosFisicosController.BuscarEspacioFisico
      parameters:
      - in: body
        name: body
        description: body for Buscar Espacio Fisico content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{init}'
        "400":
          description: the request contains incorrect syntax
  /espacios_fisicos_mid/DesactivarEspacioFisico/{id}:
    put:
      tags:
      - espacios_fisicos_mid
      description: Activar el espacio fisico
      operationId: GestionEspaciosFisicosController.PutActivarEspacioFisico
      parameters:
      - in: body
        name: body
        description: body Desactivar Espacio Fisico content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "400":
          description: the request contains incorrect syntax
  /espacios_fisicos_mid/EditarEspacioFisico:
    post:
      tags:
      - espacios_fisicos_mid
      description: Editar espacio fisico
      operationId: GestionEspaciosFisicosController.EditarEspacioFisico
      parameters:
      - in: body
        name: body
        description: body for Editar Espcaio Fisico content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{init}'
        "400":
          description: the request contains incorrect syntax
  /espacios_fisicos_mid/RegistroEspacioFisico:
    post:
      tags:
      - espacios_fisicos_mid
      description: Registro Espacio Fisico
      operationId: RegistroEspaciosFisicosController.RegistroEspacioFisico
      parameters:
      - in: body
        name: body
        description: body for Registro Espacio Fisico content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{init}'
        "400":
          description: the request contains incorrect syntax
definitions:
  '{}':
    title: '{}'
    type: object
tags:
- name: espacios_fisicos_mid
  description: |
    RegistroController operations for Registro
